package com.example.enums;

public enum Label {
    // FOR USER HISTORY
    CATEGORY_SHOWED, CATEGORY_OPENED, INNERCATEGORY_SHOWED, INNERCATEGORY_OPENED, OFFER_STARTED,

    // FOR CATEGORY ADDING
    NO_LABEL, ASKING_STARTED, CATEGORY_NAME_UZ_ASKED, CATEGORY_NAME_RU_ASKED, INNER_CATEGORY_NAME_UZ_ASKED, INNER_CATEGORY_NAME_RU_ASKED, ASKING_FINISHED
}
